server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /data/loki/positions.yaml

clients:
  - url: http://localhost:3100/loki/api/v1/push

scrape_configs:
- job_name: akumoapplogs
  static_configs:
  - targets:
      - localhost
    labels:
      job: access_logs
      host: akumoapp
      __path__: /var/log/akumoapp/access.log

- job_name: akumoapplogs
  static_configs:
  - targets:
      - localhost
    labels:
      job: error_logs
      host: akumoapp
      __path__: /var/log/akumoapp/error.log

- job_name: application
    entry_parser: raw
    static_configs:
      - targets:
          - localhost:9191
    relabel_configs:
      - source_labels: [__address__]
        target_label: __tmp_hash
        replacement: "${1}"
      - source_labels: [__tmp_hash]
        target_label: instance
      - target_label: job
        replacement: "application"

  - job_name: nginx
    entry_parser: regexp
    regexp:
      expression: '^(?P<remote_addr>[^ ]*) - (?P<remote_user>[^ ]*) \[(?P<time_local>[^\]]*)\] "(?P<request>[^ ]*) (?P<status>[^ ]*)" (?P<body_bytes_sent>[^ ]*) "(?P<http_referer>[^"]*)" "(?P<http_user_agent>[^"]*)"'
    static_configs:
      - targets:
          - localhost:9292
    relabel_configs:
      - source_labels: [__address__]
        target_label: __tmp_hash
        replacement: "${1}"
      - source_labels: [__tmp_hash]
        target_label: instance
      - target_label: job
        replacement: "nginx"